import * as React from "react";
import Box from "@mui/material/Box";
import CssBaseline from "@mui/material/CssBaseline";
import BottomNavigation from "@mui/material/BottomNavigation";
import BottomNavigationAction from "@mui/material/BottomNavigationAction";
import ImageList from "@mui/material/ImageList";
import ImageListItem from "@mui/material/ImageListItem";
import Paper from "@mui/material/Paper";
import IconButton from "@mui/material/IconButton";
import ThumbUpIcon from "@mui/icons-material/ThumbUp";
// import List from "@mui/material/List";
// import ListItem from "@mui/material/ListItem";
// import ListItemAvatar from "@mui/material/ListItemAvatar";
// import ListItemText from "@mui/material/ListItemText";
// import Avatar from "@mui/material/Avatar";
import HomeIcon from "@mui/icons-material/Home";
import ImageListItemBar from "@mui/material/ImageListItemBar";
import PersonOutlineIcon from "@mui/icons-material/PersonOutline";
import FeedIcon from "@mui/icons-material/Feed";
import { useNavigate } from "react-router-dom";

// function refreshMessages(): MessageExample[] {
//   const getRandomInt = (max: number) =>
//     Math.floor(Math.random() * Math.floor(max));

//   return Array.from(new Array(50)).map(
//     () => messageExamples[getRandomInt(messageExamples.length)]
//   );
// }

export default function FixedBottomNavigation(props) {
  const [value, setValue] = React.useState(0);
  const ref = React.useRef<HTMLDivElement>(null);

  const { highlight, feed_html, home_html, profile_html } = props;
  //   const [messages, setMessages] = React.useState(() => refreshMessages());

  const navigate = useNavigate();

  React.useEffect(() => console.log(value), [value]);

  React.useEffect(() => {
    setValue(highlight);
  }, []);
  //   React.useEffect(() => {
  //     (ref.current as HTMLDivElement).ownerDocument.body.scrollTop = 0;
  //     setMessages(refreshMessages());
  //   }, [value, setMessages]);

  return (
    <Box sx={{ pb: 7 }} ref={ref}>
      <CssBaseline />
      {/* <List>
        {messages.map(({ primary, secondary, person }, index) => (
          <ListItem button key={index + person}>
            <ListItemAvatar>
              <Avatar alt="Profile Picture" src={person} />
            </ListItemAvatar>
            <ListItemText primary={primary} secondary={secondary} />
          </ListItem>
        ))}
      </List> */}
      {feed_html || home_html || profile_html}
      <Paper
        sx={{ position: "fixed", bottom: 0, left: 0, right: 0 }}
        elevation={3}
      >
        <BottomNavigation
          value={value}
          onChange={(event, newValue) => {
            navigate(newValue);
            setValue(newValue);
          }}
        >
          <BottomNavigationAction
            label="Home"
            value="/home"
            icon={<HomeIcon />}
          />
          <BottomNavigationAction
            label="Feed"
            value="/personal_feed"
            icon={<FeedIcon />}
          />
          <BottomNavigationAction
            label="Profile"
            value="/profile"
            icon={<PersonOutlineIcon />}
          />
        </BottomNavigation>
      </Paper>
    </Box>
  );
}

// interface MessageExample {
//   primary: string;
//   secondary: string;
//   person: string;
// }

// const messageExamples: readonly MessageExample[] = [
//   {
//     primary: "Brunch this week?",
//     secondary:
//       "I'll be in the neighbourhood this week. Let's grab a bite to eat",
//     person: "/static/images/avatar/5.jpg",
//   },
//   {
//     primary: "Birthday Gift",
//     secondary: `Do you have a suggestion for a good present for John on his work
//       anniversary. I am really confused & would love your thoughts on it.`,
//     person: "/static/images/avatar/1.jpg",
//   },
//   {
//     primary: "Recipe to try",
//     secondary:
//       "I am try out this new BBQ recipe, I think this might be amazing",
//     person: "/static/images/avatar/2.jpg",
//   },
//   {
//     primary: "Yes!",
//     secondary: "I have the tickets to the ReactConf for this year.",
//     person: "/static/images/avatar/3.jpg",
//   },
//   {
//     primary: "Doctor's Appointment",
//     secondary:
//       "My appointment for the doctor was rescheduled for next Saturday.",
//     person: "/static/images/avatar/4.jpg",
//   },
//   {
//     primary: "Discussion",
//     secondary: `Menus that are generated by the bottom app bar (such as a bottom
//       navigation drawer or overflow menu) open as bottom sheets at a higher elevation
//       than the bar.`,
//     person: "/static/images/avatar/5.jpg",
//   },
//   {
//     primary: "Summer BBQ",
//     secondary: `Who wants to have a cookout this weekend? I just got some furniture
//       for my backyard and would love to fire up the grill.`,
//     person: "/static/images/avatar/1.jpg",
//   },
// ];

const itemData = [
  {
    img: "https://images.unsplash.com/photo-1551963831-b3b1ca40c98e",
    title: "Breakfast",
    author: "@bkristastucchio",
  },
  {
    img: "https://images.unsplash.com/photo-1551782450-a2132b4ba21d",
    title: "Burger",
    author: "@rollelflex_graphy726",
  },
  {
    img: "https://images.unsplash.com/photo-1522770179533-24471fcdba45",
    title: "Camera",
    author: "@helloimnik",
  },
  {
    img: "https://images.unsplash.com/photo-1444418776041-9c7e33cc5a9c",
    title: "Coffee",
    author: "@nolanissac",
  },
  {
    img: "https://images.unsplash.com/photo-1533827432537-70133748f5c8",
    title: "Hats",
    author: "@hjrc33",
  },
  {
    img: "https://images.unsplash.com/photo-1558642452-9d2a7deb7f62",
    title: "Honey",
    author: "@arwinneil",
  },
  {
    img: "https://images.unsplash.com/photo-1516802273409-68526ee1bdd6",
    title: "Basketball",
    author: "@tjdragotta",
  },
  {
    img: "https://images.unsplash.com/photo-1518756131217-31eb79b20e8f",
    title: "Fern",
    author: "@katie_wasserman",
  },
  {
    img: "https://images.unsplash.com/photo-1597645587822-e99fa5d45d25",
    title: "Mushrooms",
    author: "@silverdalex",
  },
  {
    img: "https://images.unsplash.com/photo-1567306301408-9b74779a11af",
    title: "Tomato basil",
    author: "@shelleypauls",
  },
  {
    img: "https://images.unsplash.com/photo-1471357674240-e1a485acb3e1",
    title: "Sea star",
    author: "@peterlaster",
  },
  {
    img: "https://images.unsplash.com/photo-1589118949245-7d38baf380d6",
    title: "Bike",
    author: "@southside_customs",
  },
];
